### ISSUE TITLE
for Running environment

### ISSUE THREAD

**Issue by kqsgdka** [AKASH2907/pi-consistency-activity-detection#1]
Do you have environment configuration？

**Comment by kqsgdka** [comment]
in main.py：from utils.losses import SpreadLoss, DiceLoss, IoULoss, weighted_mse_loss
There is no class IoULoss in the code

**Comment by AKASH2907** [comment]
I'll update the code this weekend. IoU Loss is not used.

**Comment by kqsgdka** [comment]
thank you.
