### ISSUE TITLE
IoULoss

### ISSUE THREAD

**Issue by gshuangchun** [AKASH2907/pi-consistency-activity-detection#2]
Hi,
Nice work!
But I can't find the IoULoss in the utils/losses.py. Could you please update it?
Thank you!

**Comment by gshuangchun** [comment]
Thank you for your reply!
Could you please upload the train_annots_20_labeled.pkl as soon as possible?

**Comment by AKASH2907** [comment]
Pickle files have been uploaded. The link is on the main readme page.
