### ISSUE TITLE
requirements problem

### ISSUE THREAD

**Issue by bamaolalala** [AKASH2907/pi-consistency-activity-detection#5]
Hi,
Nice work!
But I don't know -e /home/ak119590/gait/training_codes/exp_1_basic_3d_train/transformers_train/timesformer  in requirements.

How do I get it？

**Comment by bamaolalala** [comment]
Also
@file:///URL Available only on local file systems
can you regenerate the Requirements file？
you can consider using the following command for the time being
 pip list --format=freeze > requirements.txt

**Comment by bamaolalala** [comment]
How should I test it please?

**Comment by AKASH2907** [comment]
I've updated the evaluation file.
