### ISSUE TITLE
Cloud you provide the   test_annots.pkl  ？

### ISSUE THREAD

**Issue by yayaygaga** [AKASH2907/pi-consistency-activity-detection#6]
Thanks for your awesome work!
Cloud you provide the   test_annots.pkl  for test ?

**Comment by AKASH2907** [comment]
Uploaded at the same link for pickle files.

**Comment by yayaygaga** [comment]
when I val the model，I got an error：

start_frame, end_frame, label, labeled_vid = ann[0], ann[1], ann[2], ann[5]
IndexError: tuple index out of range

Is the test_annots.pkl incomplete or I need use other data to val?

**Comment by yayaygaga** [comment]
Is running the JHMDB dataset using the same code?

**Comment by AKASH2907** [comment]
Not really, I will update the evaluation file and dataloader on the weekend.

**Comment by bamaolalala** [comment]
I'm really sorry to bother you again. When will the complete code of JHMDB be updated

**Comment by AKASH2907** [comment]
Hi, I've updated everything. Have a look.
