### ISSUE TITLE
 annotation format

### ISSUE THREAD

**Issue by ccx2022** [AKASH2907/pi-consistency-activity-detection#7]
Thank you for your excellent work on this paper！
Could you please provide the dataset annotation format of the following annotation files ?

-testing_annots.pkl
-train_annots_20_labeled_random.pkl
-train_annots_80_unlabeled_random.pkl

**Comment by AKASH2907** [comment]
Annotation format can be visualized while loading pickle file in the data loader.
However, this is the common format for all files- 
{video_name, start_frame, end_frame, video_class, bboxes, frame-ids, 0/1 - labeled/unlabeled}

**Comment by ccx2022** [comment]
Okay, Thank you very much。
